name: Cron

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 20
    - run: node main.js
